# Generated by Django 6.0.6 on 2026-07-03 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_add_post_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('nudity', 'Nudity or sexual activity'), ('hate_speech', 'Hate speech or symbols'), ('violence', 'Violence or dangerous organizations'), ('illegal_goods', 'Sale of illegal or regulated goods'), ('bullying', 'Bullying or harassment'), ('intellectual_property', 'Intellectual property violation'), ('self_injury', 'Suicide or self-injury'), ('eating_disorders', 'Eating disorders'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('dislike', "I just don't like it"), ('other', 'Something else')], default='other', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.postcomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'reporter'), name='unique_comment_report')],
            },
        ),
    ]
