# Generated by Django 6.0.6 on 2026-07-06 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_commentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='postcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('pinned', True)), fields=('post',), name='unique_pinned_comment_per_post'),
        ),
    ]
