# Generated by Django 6.0.6 on 2026-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_neatpointsaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending transcode'), ('processing', 'Transcoding'), ('failed', 'Transcode failed')], db_index=True, default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
