# Generated by Django 6.0.6 on 2026-08-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postmedia_attempts_postmedia_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumb_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
