# Generated by Django 6.0.6 on 2026-08-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postmedia_thumb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
