# Generated by Django 6.0.6 on 2026-07-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category_event_date_eventreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('nudity', 'Nudity or sexual activity'), ('hate_speech', 'Hate speech or symbols'), ('violence', 'Violence or dangerous organizations'), ('illegal_goods', 'Sale of illegal or regulated goods'), ('bullying', 'Bullying or harassment'), ('intellectual_property', 'Intellectual property violation'), ('self_injury', 'Suicide or self-injury'), ('eating_disorders', 'Eating disorders'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('dislike', "I just don't like it"), ('other', 'Something else')], default='other', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='eventcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('pinned', True)), fields=('event',), name='unique_pinned_comment_per_event'),
        ),
        migrations.AddField(
            model_name='eventcommentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.eventcomment'),
        ),
        migrations.AddField(
            model_name='eventcommentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventcommentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter'), name='unique_event_comment_report'),
        ),
    ]
