# Generated by Django 6.0.6 on 2026-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_messages', '0002_messagereaction_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
