# Generated by Django 6.0.6 on 2026-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_messages', '0004_message_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
