# Generated by Django 6.0.6 on 2026-08-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_messages', '0005_conversationmember_hidden_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='opens',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_mode',
            field=models.CharField(blank=True, choices=[('once', 'View once'), ('replay', 'Allow replay')], default='', max_length=6),
        ),
    ]
