# Generated by Django 6.0.6 on 2026-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_messages', '0007_messageopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
