# Generated by Django 6.0.6 on 2026-08-03 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.TextField()),
                ('resolved_url', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('image_url', models.TextField(blank=True, default='')),
                ('site_name', models.CharField(blank=True, default='', max_length=100)),
                ('ok', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='linkpreview_fetched_14a9dc_idx')],
            },
        ),
    ]
