# Generated by Django 6.0.6 on 2026-08-04 07:25

from django.db import migrations, models


def clear_cache(apps, schema_editor):
    """Drop every cached card so the new fields get filled in.

    Rows written before this migration have no author, no kind and no image
    dimensions, and they stay fresh for a week — so without this, a TikTok
    already shared in a chat would keep rendering the old author-less card
    long after the deploy. This table is only a cache; every row rebuilds
    itself the next time someone views the link.
    """
    apps.get_model('linkpreview', 'LinkPreview').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linkpreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpreview',
            name='author_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='author_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(clear_cache, migrations.RunPython.noop),
    ]
