# Generated by Django 6.0.6 on 2026-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_create_official_events',
            field=models.BooleanField(default=False),
        ),
    ]
