# Generated by Django 6.0.6 on 2026-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_can_create_official_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_comment_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
