# Generated by Django 6.0.6 on 2026-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_target_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_full_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
