# Generated by Django 6.0.6 on 2026-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_avatar_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumb_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
