# Generated by Django 6.0.6 on 2026-08-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_so_user_id_0a462a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_social_identity')],
            },
        ),
    ]
