# Generated by Django 6.0.6 on 2026-08-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_pending',
            field=models.BooleanField(default=False),
        ),
    ]
