# Generated by Django 6.0.6 on 2026-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_username_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
