# Generated by Django 6.0.6 on 2026-08-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_city_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_changed_at',
        ),
    ]
