# Generated by Django 6.0.6 on 2026-09-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('payout_per_signup', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('daily_cap', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassadors_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'web'), ('app', 'app')], db_index=True, default='web', max_length=4)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visitor', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ambassadors.ambassador')),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('qualified', 'qualified'), ('approved', 'approved'), ('paid', 'paid'), ('flagged', 'flagged'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=10)),
                ('flags', models.TextField(blank=True, default='')),
                ('has_city', models.BooleanField(default=False)),
                ('post_count', models.IntegerField(default=0)),
                ('retained_day3', models.BooleanField(default=False)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='ambassadors.ambassador')),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signup', to='ambassadors.ambassadorclick')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_signup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='ambassadorclick',
            index=models.Index(fields=['ambassador', 'source', '-created'], name='ambassadors_ambassa_6b027a_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorsignup',
            index=models.Index(fields=['ambassador', 'status'], name='ambassadors_ambassa_3b7df4_idx'),
        ),
    ]
