# Generated by Django 6.0.6 on 2026-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsignup',
            name='claim_method',
            field=models.CharField(choices=[('token', 'token'), ('referrer', 'referrer'), ('clipboard', 'clipboard'), ('network', 'network')], default='token', max_length=10),
        ),
    ]
