# Generated by Django 6.0.6 on 2026-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0002_ambassadorsignup_claim_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorsignup',
            name='interaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
