# Generated by Django 6.0.6 on 2026-09-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0005_ambassador_custom_slogan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorsignup',
            name='claim_method',
            field=models.CharField(choices=[('token', 'token'), ('referrer', 'referrer'), ('clipboard', 'clipboard'), ('network', 'network'), ('content', 'content')], default='token', max_length=10),
        ),
        migrations.AlterField(
            model_name='ambassadorsignup',
            name='click',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signup', to='ambassadors.ambassadorclick'),
        ),
        migrations.CreateModel(
            name='AmbassadorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram_story', 'Instagram story'), ('instagram_post', 'Instagram post'), ('instagram_reel', 'Instagram reel'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('other', 'Άλλο')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('city', models.CharField(max_length=120)),
                ('uploaded_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='ambassadors.ambassador')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='ambassadorsignup',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signups', to='ambassadors.ambassadorcontent'),
        ),
        migrations.AddIndex(
            model_name='ambassadorcontent',
            index=models.Index(fields=['status', 'city', 'uploaded_at'], name='ambassadors_status_c983a6_idx'),
        ),
    ]
