"""Add AmbassadorClick.confirmed, and say what it should be for rows that
predate it.

New rows are settled by the page itself. These cannot be, so the backfill
falls back to what each row was fetched with — see ambassadors/bots.py. It is
a judgement about the past, not a rule the site runs on, and it is deliberately
generous: anything not recognisably a crawler is treated as a person, so this
understates nobody's numbers.
"""

# Generated by Django 6.0.6 on 2026-09-23 08:03

from django.db import migrations, models

from ambassadors.bots import looks_automated


def backfill(apps, schema_editor):
    Click = apps.get_model('ambassadors', 'AmbassadorClick')
    # An installed app asking for a token was always a device.
    Click.objects.filter(source='app').update(confirmed=True)

    human = [
        click.id
        for click in Click.objects.filter(source='web').only(
            'id', 'user_agent', 'ip_address').iterator()
        if not looks_automated(click.user_agent, click.ip_address)
    ]
    for start in range(0, len(human), 500):
        Click.objects.filter(id__in=human[start:start + 500]).update(confirmed=True)


def unbackfill(apps, schema_editor):
    """Nothing to undo: the column goes with it."""


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0008_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorclick',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
