"""Give every ambassador the PIN that neatapp.gr/c/<code> asks for.

AddField computes a default once and writes that one value to every existing
row, which for a secret is the same as having none: each creator is given
their own here instead.
"""

# Generated by Django 6.0.6 on 2026-09-23 08:27

from django.db import migrations, models

from ambassadors.models import new_dashboard_pin


def issue_pins(apps, schema_editor):
    Ambassador = apps.get_model('ambassadors', 'Ambassador')
    for ambassador in Ambassador.objects.all().only('id'):
        Ambassador.objects.filter(id=ambassador.id).update(
            dashboard_pin=new_dashboard_pin())


def drop_pins(apps, schema_editor):
    """Nothing to undo: the column goes with it."""


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0009_click_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='dashboard_pin',
            field=models.CharField(default=new_dashboard_pin, max_length=6),
        ),
        migrations.RunPython(issue_pins, drop_pins),
    ]
