# Generated by Django 6.0.6 on 2026-07-22 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('actor_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('mfa', models.CharField(blank=True, default='none', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('entry_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-created', 'severity'], name='neat_securi_created_75d295_idx'), models.Index(fields=['event_type', '-created'], name='neat_securi_event_t_4ef0a9_idx')],
            },
        ),
    ]
