# Generated by Django 6.0.6 on 2026-09-16 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sent', 'sent'), ('opened', 'opened'), ('joined', 'joined')], db_index=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('visitor', models.CharField(blank=True, db_index=True, max_length=64)),
                ('day', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_events', to=settings.AUTH_USER_MODEL)),
                ('joined_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_join', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['inviter', 'kind'], name='invites_inv_inviter_5e234c_idx')],
            },
        ),
    ]
