# Generated by Django 6.0.6 on 2026-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteevent',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
