"""
Django settings for neatbackend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY on the server — this fallback is only for local dev
# and is not safe to rely on in production (it's committed to source).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-su$035ic-$$sue1l*l!4#dzl&qh#!@-0^wq@ej8r3ofzyp@83+',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off; set DJANGO_DEBUG=True in your local shell if you want it.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['*']

if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_hostname)

# DM messages (photos/GIFs) are sent as base64 inside a raw JSON body, which is well over
# Django's 2.5MB default. Requests over the limit fail request.body access entirely, which
# dm_messages._json_body swallows as "Invalid JSON" -- the client then leaves an unconfirmed,
# undeletable optimistic message stuck in the thread.
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'corsheaders',
    'accounts.apps.AccountsConfig',
    'posts',
    'dm_messages.apps.DmMessagesConfig',
    'events.apps.EventsConfig',
    'push.apps.PushConfig',
    'security.apps.SecurityConfig',
    'linkpreview.apps.LinkPreviewConfig',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # First, so every serializer below knows what the caller can render.
    'accounts.client_version.ClientVersionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Last: sees the final status code, and only records security-relevant
    # events (probes, denials, volume) rather than all traffic.
    'security.middleware.SecurityAuditMiddleware',
]

ROOT_URLCONF = 'neatbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neatbackend.wsgi.application'
ASGI_APPLICATION = 'neatbackend.asgi.application'

# Channel layer for the DM WebSocket (see dm_messages/consumers.py). Redis is
# required in production — gunicorn runs multiple worker processes, and only
# a shared (not in-memory) layer lets a message sent in one process reach a
# socket connected to another. REDIS_URL unset falls back to the in-memory
# layer purely so `manage.py runserver` works without installing Redis
# locally; that fallback is never correct for the real multi-worker deploy.
_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_name = os.environ.get('DB_NAME', '').strip()
_database_url = os.environ.get('DATABASE_URL', '').strip()

if _db_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _db_name,
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', ''),
            'PORT': os.environ.get('DB_PORT', '3306'),
            # The database is a *managed* instance on another host, so every
            # connection is a network round trip plus a TLS handshake. At the
            # default of 0 that cost is paid again on every single request,
            # which is latency no query tuning can win back. 60s reuses a
            # connection across requests without holding one open so long that
            # a restarted database leaves workers talking to a dead socket.
            'CONN_MAX_AGE': 60,
            # Cheap liveness check before a reused connection is handed out,
            # so a connection the server closed in the meantime is replaced
            # rather than raising to the caller. (Django 4.1+.)
            'CONN_HEALTH_CHECKS': True,
        }
    }
elif _database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Absolute base for URLs we hand to clients for our own files.
#
# Link-preview thumbnails are copied onto our disk and served from /media/, but
# the app loads them with Image.network, which needs an absolute URL. Kept
# host-agnostic in the database (a bare /media/... path) and made absolute on
# the way out, so moving off the pinned IP to api.neatapp.gr is a config change
# rather than a data migration.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'https://63.181.201.175').rstrip('/')


# ── Sign in with Apple / Google ──────────────────────────────────────────────
#
# The audiences an incoming ID token is allowed to name. A token is only ever
# trusted if its `aud` is one of these, because a perfectly valid token issued
# to somebody else's app would otherwise be accepted as proof of identity here.
#
# Apple: the app's bundle id (and the Services ID, if the web flow is ever added).
#
# Google: the two platforms name *different* audiences, and both have to be
# listed or one of them cannot sign in at all.
#
#   * iOS goes through Google's own SDK, which mints a token addressed to the
#     iOS client id.
#   * Android goes through Credential Manager, which has no Android-specific
#     audience to use — the Android OAuth client exists only so Google can
#     recognise the package name and signing certificate — so the token it
#     mints is addressed to the *web* client id instead, the same value the app
#     passes as its serverClientId.
#
# These are public identifiers, not secrets; they already ship inside the app
# binary. They are defaulted rather than left to the environment because an
# incomplete list fails as "that sign-in was not issued for this app" on one
# platform only, which reads like an app bug rather than a missing variable.
def _id_list(name, default=''):
    return tuple(v.strip() for v in os.environ.get(name, default).split(',') if v.strip())


APPLE_CLIENT_IDS = _id_list('APPLE_CLIENT_IDS', 'NeatApp.Neat')
GOOGLE_CLIENT_IDS = _id_list(
    'GOOGLE_CLIENT_IDS',
    '449378002358-i3dlqsb7rmff8jf05ag6slk7o21k8laq.apps.googleusercontent.com,'
    '449378002358-430tlsk1shjrk07mv4nbcsjibtk9437a.apps.googleusercontent.com',
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The app serves one country, so "today" and "3pm" mean Greek time to everyone
# who reads them. Storage is unaffected: USE_TZ keeps every timestamp in the
# database in UTC, and this only decides what they are converted to on the way
# out — the analytics page, template output, and timezone.localtime().
#
# Safe on this database: named-zone CONVERT_TZ is what TruncDate compiles to
# under a non-UTC zone, and the server has the timezone tables loaded (checked:
# 1792 names). Without them those queries would silently return nothing.
TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = True

# DB-backed so rate-limit counters (accounts/ratelimit.py) are shared
# correctly across all gunicorn worker processes, not just per-process.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# Security headers/cookie flags. The app is served over both HTTP (:80) and
# HTTPS (:443) for now — the Netlify-hosted web build's server-side proxy
# still targets the plain-HTTP port because it can't validate our self-signed
# cert, so we can't force an HTTP->HTTPS redirect without breaking it. These
# settings are the ones that don't depend on that.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Email (Gmail SMTP) — password reset depends on these.
#
# Required env vars on the server:
#   EMAIL_HOST_USER      the full Gmail address that sends the mail
#   EMAIL_HOST_PASSWORD  a Google App Password (16 chars, 2FA must be on).
#                        Google refuses normal account passwords over SMTP.
#
# DEFAULT_FROM_EMAIL falls back to EMAIL_HOST_USER on purpose: Gmail only lets
# you send as the authenticated account (or an alias configured on it), so a
# different From address is refused. Don't set it to a domain the Gmail account
# can't send as.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Carry a display name, otherwise mail clients fall back to showing the mailbox
# name ("neatgreece"). The address still has to be the authenticated Gmail
# account — only the label in front of it is free.
EMAIL_FROM_NAME = os.environ.get('EMAIL_FROM_NAME', 'Neat')
_default_sender = (
    f'{EMAIL_FROM_NAME} <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'noreply@neat.app'
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', _default_sender)

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Where clients are told to fetch media from. Empty means "from this server",
# which is the current behaviour. Set it to a CloudFront domain and every media
# URL in an API response is rewritten to point at the edge instead — see
# neatbackend/cdn.py. Files do not move; only the address changes.
MEDIA_CDN_URL = os.environ.get('MEDIA_CDN_URL', '').strip()

# Firebase Cloud Messaging — path to the service-account JSON downloaded from
# Firebase console (Project settings → Service accounts). Never commit this
# file; defaults to a gitignored path next to manage.py for local dev, and
# should be set via the env var on the server.
FIREBASE_CREDENTIALS_PATH = os.environ.get(
    'FIREBASE_CREDENTIALS_PATH', str(BASE_DIR / 'firebase-service-account.json')
)
